CREATE TABLE User (
   UserID INT AUTO_INCREMENT,
   Email VARCHAR(100) NOT NULL UNIQUE,
   Username VARCHAR(50) NOT NULL UNIQUE,
   Password VARCHAR(255) NOT NULL,
   Role ENUM('Admin', 'User') NOT NULL,
   PRIMARY KEY(UserID)
);

CREATE TABLE Recipe (
   RecipeID INT AUTO_INCREMENT,
   Title VARCHAR(100) NOT NULL,
   Description TEXT,
   Ingredients TEXT NOT NULL,
   Instructions TEXT NOT NULL,
   CookingTime INT NOT NULL,
   Difficulty ENUM('Easy', 'Medium', 'Hard') NOT NULL,
   CreatedBy INT NOT NULL,
   AverageRating DECIMAL(3,2) DEFAULT NULL,
   ImageURL VARCHAR(255) DEFAULT NULL,
   PRIMARY KEY (RecipeID),
   FOREIGN KEY (CreatedBy) REFERENCES User(UserID) ON DELETE CASCADE
);


CREATE TABLE Comment (
   CommentID INT AUTO_INCREMENT,
   Content TEXT DEFAULT NULL,
   RecipeID INT NOT NULL,
   UserID INT NOT NULL,
   PRIMARY KEY(CommentID),
   FOREIGN KEY(RecipeID) REFERENCES Recipe(RecipeID) ON DELETE CASCADE,
   FOREIGN KEY(UserID) REFERENCES User(UserID) ON DELETE CASCADE
);

CREATE TABLE Favorite (
   UserID INT NOT NULL,
   RecipeID INT NOT NULL,
   PRIMARY KEY(UserID, RecipeID),
   FOREIGN KEY(UserID) REFERENCES User(UserID) ON DELETE CASCADE,
   FOREIGN KEY(RecipeID) REFERENCES Recipe(RecipeID) ON DELETE CASCADE
);

CREATE TABLE Rate (
   UserID INT NOT NULL,
   RecipeID INT NOT NULL,
   Rating TINYINT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
   PRIMARY KEY(UserID, RecipeID),
   FOREIGN KEY(UserID) REFERENCES User(UserID) ON DELETE CASCADE,
   FOREIGN KEY(RecipeID) REFERENCES Recipe(RecipeID) ON DELETE CASCADE
);
